### ISSUE TITLE
Scenario for Asset that only cares about total booking amount

### ISSUE THREAD

**Issue by ericeric284** [EasyAbp/BookingService#5]
Hi , Our team is dicussing a scenario described below, hope that you can help us figure out the best practice.

For example, there's a pool asset, which can Contain 500 people at most.
In the morning, we allow only 200 people to book the pool (08:00 ~12:00).
In the afternoon, we allow all 500 people to book the pool (14:00 ~18:00).

If we use current model , we will have to build 500 asset for this pool,
and create periods for morning (08:00 ~12:00) and afternoon(14:00 ~18:00).

Maybe there's better ways to handle this type of asset, which only cares about total booking amount?

**Comment by gdlcf88** [comment]
Under the current design, we should create 500 "Player" assets in the "Pool" category with the blacklist mode. 200 of the player assets should have "reject" schedules all afternoon.

The real issue is that if the player number reaches 10000+, we will face a performance problem. Adding a new `Quantity` property in the Asset entity is a solution, but it may cause more complexities.

Do you have any other ideas?

**Comment by gdlcf88** [comment]
Let's return to your dynamic quantity need. If the Quantity property in the Asset entity adds, the dynamic-quantity scene can implement on the app development side. You can create a new aggregate root named `AssetPeriodQuantity` and then override the AssetOccupancyManager to use it.
